# docker-compose.yml

volumes:
  pg_data:
  static:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: iadzhak/taski_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
    restart: always

  frontend:
    image: iadzhak/taski_frontend
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
    restart: always
    
  gateway:
    image: iadzhak/taski_gateway
    ports:
      - 8000:80
    depends_on:
      - backend
    volumes:
      - static:/staticfiles
    restart: always
